"""L3 ragged batching: exact padding masks and parity with the L2 CPU oracle.

Fixtures are generated by the oracle's own push-forward so the two sides cannot
drift: the oracle produces conditional targets, this module converts them into
snapshot-shaped loss rows, and both evaluate the same logits.
"""

from __future__ import annotations

import pytest

torch = pytest.importorskip("torch")

from mage_ptcg.meta_specialist.local_dataset_v2 import (  # noqa: E402
    canonical_json_bytes_v2,
)
from mage_ptcg.meta_specialist.neural_batch_v1 import (  # noqa: E402
    NeuralBatchV1Error,
    WeightedLossAccumulatorV1,
    build_ragged_step_batch_v1,
    masked_log_softmax_v1,
    require_finite_update_v1,
    weighted_semantic_loss_v1,
)
from mage_ptcg.meta_specialist.reference_losses_v1 import (  # noqa: E402
    CompleteActionMassRowV1,
    ReferenceLogitRowV1,
    ReferenceLossExampleInputV1,
    SemanticClassV1,
    SemanticSelectionSpaceV1,
    evaluate_reference_losses_v1,
    push_forward_complete_action_mass_v1,
)


def _semantic(name: str) -> dict[str, object]:
    # Any canonical JSON object works: only its canonical bytes are the identity.
    return {"class": name}


def _token(name: str) -> bytes:
    return canonical_json_bytes_v2(_semantic(name))


def _payload_by_token(names) -> dict[bytes, dict[str, object]]:
    return {_token(name): _semantic(name) for name in names}


def _space(names, *, minimum: int, maximum: int) -> SemanticSelectionSpaceV1:
    return SemanticSelectionSpaceV1(
        classes=tuple(SemanticClassV1(_token(name), 1) for name in names),
        minimum=minimum,
        maximum=maximum,
        order_semantics="unordered",
    )


def _targets(names, selections, *, minimum: int, maximum: int, quality: float):
    space = _space(names, minimum=minimum, maximum=maximum)
    rows = tuple(
        CompleteActionMassRowV1(tuple(_token(name) for name in selection), mass)
        for selection, mass in selections
    )
    return push_forward_complete_action_mass_v1(space, rows, quality_weight=quality)


def _example_from_targets(targets, names) -> dict[str, object]:
    """Convert oracle conditional targets into snapshot-shaped loss rows."""
    payloads = _payload_by_token(names)
    rows = []
    for target in targets.conditional_targets:
        token_masses = [
            {"kind": "semantic", "semantic_action": payloads[token], "mass": mass}
            for token, mass in zip(
                target.semantic_tokens, target.semantic_target_masses, strict=True
            )
        ]
        if target.stop_available:
            token_masses.append({"kind": "stop", "mass": target.stop_target_mass})
        rows.append({
            "semantic_prefix": [payloads[token] for token in target.semantic_prefix],
            "token_masses": token_masses,
            "reach_mass": target.reach_mass,
        })
    return {"loss_rows": rows, "example_quality_weight": targets.quality_weight}


NAMES_WIDE = ("a", "b", "c")
NAMES_NARROW = ("a", "b")


def _fixture():
    """Two examples with different row counts, widths, STOP presence, and weights."""
    wide = _targets(
        NAMES_WIDE,
        ((("a",), 0.3), (("b",), 0.2), (("a", "b"), 0.3), (("a", "c"), 0.2)),
        minimum=1, maximum=2, quality=0.7,
    )
    narrow = _targets(
        NAMES_NARROW, ((("a",), 0.6), (("b",), 0.4)), minimum=1, maximum=1, quality=1.0,
    )
    examples = [
        _example_from_targets(wide, NAMES_WIDE),
        _example_from_targets(narrow, NAMES_NARROW),
    ]
    return examples, (wide, narrow)


def _logits(batch, seed: int = 17):
    torch.manual_seed(seed)
    return torch.randn(batch.rows, batch.max_tokens, dtype=torch.float64)


def _oracle(all_targets, logits, batch):
    inputs = []
    cursor = 0
    for targets in all_targets:
        logit_rows = []
        for target in targets.conditional_targets:
            width = len(target.semantic_tokens)
            logit_rows.append(
                ReferenceLogitRowV1(
                    semantic_prefix=target.semantic_prefix,
                    semantic_tokens=target.semantic_tokens,
                    stop_available=target.stop_available,
                    semantic_logits=tuple(
                        float(logits[cursor, i]) for i in range(width)
                    ),
                    stop_logit=(
                        float(logits[cursor, width]) if target.stop_available else None
                    ),
                )
            )
            cursor += 1
        inputs.append(
            ReferenceLossExampleInputV1(targets=targets, logit_rows=tuple(logit_rows))
        )
    assert cursor == batch.rows
    return evaluate_reference_losses_v1(tuple(inputs))


def test_batch_pads_only_to_the_batch_local_maximum_with_exact_masks() -> None:
    examples, _targets_out = _fixture()
    batch = build_ragged_step_batch_v1(examples)

    widths = batch.token_mask.sum(dim=-1).tolist()
    assert batch.max_tokens == max(widths)
    assert min(widths) < max(widths)  # the batch really is ragged
    assert float(batch.target_masses[~batch.token_mask].abs().sum()) == 0.0
    assert batch.quality_weight.tolist() == [0.7, 1.0]
    assert float(batch.weight_sum()) == pytest.approx(1.7)
    assert batch.example_index.tolist() == sorted(batch.example_index.tolist())


def test_narrow_batch_does_not_inherit_a_wider_batch_width() -> None:
    examples, _targets_out = _fixture()
    wide = build_ragged_step_batch_v1(examples)
    narrow = build_ragged_step_batch_v1([examples[1]])
    assert narrow.max_tokens < wide.max_tokens


def test_masked_log_softmax_ignores_padding_and_never_leaks_gradient() -> None:
    examples, _targets_out = _fixture()
    batch = build_ragged_step_batch_v1(examples)
    logits = _logits(batch).requires_grad_(True)

    log_probabilities = masked_log_softmax_v1(logits, batch.token_mask)
    valid = log_probabilities.exp() * batch.token_mask
    assert torch.allclose(valid.sum(dim=-1), torch.ones(batch.rows, dtype=torch.float64))
    assert float(log_probabilities.detach()[~batch.token_mask].abs().sum()) == 0.0

    poisoned = logits.detach().clone()
    poisoned[~batch.token_mask] = 1e9
    assert torch.allclose(
        masked_log_softmax_v1(poisoned, batch.token_mask)[batch.token_mask],
        log_probabilities.detach()[batch.token_mask],
    )

    log_probabilities.sum().backward()
    assert float(logits.grad[~batch.token_mask].abs().sum()) == 0.0
    assert torch.isfinite(logits.grad).all()


def test_loss_and_gradients_match_the_cpu_oracle() -> None:
    examples, all_targets = _fixture()
    batch = build_ragged_step_batch_v1(examples)
    logits = _logits(batch).requires_grad_(True)

    weighted, weight = weighted_semantic_loss_v1(logits, batch)
    mean = weighted / weight
    mean.backward()

    oracle = _oracle(all_targets, logits.detach(), batch)
    assert float(weight.detach()) == pytest.approx(oracle.weight_sum, abs=1e-15)
    assert float(weighted.detach()) == pytest.approx(oracle.weighted_loss_sum, abs=1e-12)
    assert float(mean.detach()) == pytest.approx(oracle.mean_loss, abs=1e-12)

    cursor = 0
    for example_gradient in oracle.mean_gradients:
        for row in example_gradient.rows:
            width = len(row.semantic_gradients)
            assert logits.grad[cursor, :width].tolist() == pytest.approx(
                list(row.semantic_gradients), abs=1e-12
            )
            if row.stop_available:
                assert float(logits.grad[cursor, width]) == pytest.approx(
                    row.stop_gradient, abs=1e-12
                )
            assert float(logits.grad[cursor, width + int(row.stop_available):].abs().sum()) == 0.0
            cursor += 1
    assert cursor == batch.rows


def test_microbatch_accumulation_is_identical_to_the_whole_batch() -> None:
    examples, _targets_out = _fixture()
    whole = build_ragged_step_batch_v1(examples)
    base = _logits(whole)

    full = base.clone().requires_grad_(True)
    weighted, weight = weighted_semantic_loss_v1(full, whole)
    (weighted / weight).backward()

    accumulator = WeightedLossAccumulatorV1()
    parts = []
    cursor = 0
    for example in examples:
        micro = build_ragged_step_batch_v1([example])
        part = base[cursor : cursor + micro.rows, : micro.max_tokens].clone()
        part.requires_grad_(True)
        parts.append((part, micro, cursor))
        accumulator.add(*weighted_semantic_loss_v1(part, micro))
        cursor += micro.rows
    accumulator.mean().backward()

    assert float(accumulator.weight_sum) == pytest.approx(float(weight.detach()), abs=1e-15)
    assert float(accumulator.mean().detach()) == pytest.approx(
        float((weighted / weight).detach()), abs=1e-15
    )
    for part, micro, offset in parts:
        expected = full.grad[offset : offset + micro.rows, : micro.max_tokens]
        assert torch.allclose(part.grad, expected, atol=1e-15, rtol=0.0)


def test_zero_quality_weight_example_contributes_nothing() -> None:
    examples, _targets_out = _fixture()
    batch = build_ragged_step_batch_v1(examples)
    logits = _logits(batch)

    zeroed = build_ragged_step_batch_v1(
        [dict(examples[0], example_quality_weight=0.0), examples[1]]
    )
    weighted, weight = weighted_semantic_loss_v1(logits, zeroed)

    second = build_ragged_step_batch_v1([examples[1]])
    offset = batch.rows - second.rows
    expected_weighted, expected_weight = weighted_semantic_loss_v1(
        logits[offset:, : second.max_tokens], second
    )
    assert float(weight) == pytest.approx(float(expected_weight), abs=1e-15)
    assert float(weighted) == pytest.approx(float(expected_weighted), abs=1e-12)


def test_nonfinite_logits_and_updates_fail_closed() -> None:
    examples, _targets_out = _fixture()
    batch = build_ragged_step_batch_v1(examples)
    logits = _logits(batch)
    logits[0, 0] = float("nan")
    with pytest.raises(NeuralBatchV1Error, match="finite on every valid slot"):
        weighted_semantic_loss_v1(logits, batch)

    with pytest.raises(NeuralBatchV1Error, match="refusing the optimizer step"):
        require_finite_update_v1(torch.tensor([1.0, float("inf")]), field="gradient")
    require_finite_update_v1(torch.tensor([1.0, 2.0]), field="gradient")


def test_batch_rejects_malformed_rows_and_empty_input() -> None:
    with pytest.raises(NeuralBatchV1Error, match="at least one example"):
        build_ragged_step_batch_v1([])
    with pytest.raises(NeuralBatchV1Error, match="at least one trainable row"):
        build_ragged_step_batch_v1([{"loss_rows": [], "example_quality_weight": 1.0}])

    def one_row(token_masses):
        return {
            "loss_rows": [
                {"semantic_prefix": [], "token_masses": token_masses, "reach_mass": 1.0}
            ],
            "example_quality_weight": 1.0,
        }

    with pytest.raises(NeuralBatchV1Error, match="STOP"):
        build_ragged_step_batch_v1([one_row([
            {"kind": "stop", "mass": 0.5},
            {"kind": "semantic", "semantic_action": _semantic("a"), "mass": 0.5},
        ])])
    with pytest.raises(NeuralBatchV1Error, match="unknown kind"):
        build_ragged_step_batch_v1([one_row([{"kind": "other", "mass": 1.0}])])
