"""Automated API reference generator.

Scans the public symbols of the package and generates Markdown documentation.
"""

from __future__ import annotations
import inspect
from typing import Any

def generate_api_reference() -> str:
    """Reflectively scan modules and generate Markdown documentation."""
    modules_to_scan = [
        "contracts",
        "statistics",
        "ratings",
        "registries",
        "errors",
        "json_schema"
    ]

    lines = [
        "# Support Platform API Reference Documentation",
        "",
        "This documentation is reflectively generated by `api_docs.py` scanning the public API.",
        ""
    ]

    for mod_name in modules_to_scan:
        full_name = f"mage_ptcg.offline_training_v1_support.{mod_name}"
        try:
            mod = __import__(full_name, fromlist=["*"])
        except Exception as exc:
            lines.append(f"## Module `{mod_name}` (Failed to import: {exc})")
            continue

        lines.append(f"## Module `{mod_name}`")
        doc = inspect.getdoc(mod) or "No module docstring."
        lines.append(doc)
        lines.append("")

        for sym_name in sorted(dir(mod)):
            if sym_name.startswith("_"):
                continue
            sym = getattr(mod, sym_name)

            if inspect.isfunction(sym) or inspect.isclass(sym):
                sym_mod = getattr(sym, "__module__", None)
                if sym_mod != full_name:
                    continue

                sym_type = "class" if inspect.isclass(sym) else "function"
                lines.append(f"### `{sym_name}` ({sym_type})")

                try:
                    sig = str(inspect.signature(sym))
                    lines.append(f"**Signature**: `{sym_name}{sig}`")
                except Exception:
                    pass

                sym_doc = inspect.getdoc(sym) or "No docstring."
                lines.append(sym_doc)
                lines.append("")

    return "\n".join(lines)
