#!/usr/bin/env python3
"""Create a truthful compact handoff for the intervention lifecycle."""
from __future__ import annotations
import argparse,csv,json,hashlib,subprocess
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
PREV=Path('/home/bfe-lab-ono/kaggle/handoff-artifacts/competition-calibration-teacher-residual-v1-20260726_191500')
def rows(p):return list(csv.DictReader(p.open(encoding='utf-8',newline=''))) if p.exists() else []
def write(p,s):p.parent.mkdir(parents=True,exist_ok=True);p.write_text(s,encoding='utf-8')
def table(p,rs):
 f=sorted({k for r in rs for k in r}) or ['status'];p.parent.mkdir(parents=True,exist_ok=True)
 with p.open('w',encoding='utf-8',newline='') as h:w=csv.DictWriter(h,fieldnames=f);w.writeheader();w.writerows(rs)
def main():
 a=argparse.ArgumentParser();a.add_argument('--artifact-root',type=Path,required=True);x=a.parse_args();r=x.artifact_root
 for d in ('00_repository','01_round_robin_analysis','02_family_and_teacher_selection','03_policy_compatibility','04_proposal_collection','05_disagreement_contexts','06_intervention_screen','07_intervention_validation','08_override_table','09_residual_training','10_residual_evaluation','11_calibration_update','12_holdout','13_submission_decision','14_tests','evidence'):(r/d).mkdir(parents=True,exist_ok=True)
 rr=rows(PREV/'06_teacher_round_robin/teacher_round_robin.csv');pairs=[]
 for v in rr:
  g=int(v['games']);a_w=int(v['a_wins']);pairs.append({**v,'a_losses':g-a_w,'a_win_rate':a_w/g,'ci95_half_width':1.96*((a_w/g)*(1-a_w/g)/g)**.5})
 table(r/'01_round_robin_analysis/round_robin_pair_results.csv',pairs);table(r/'01_round_robin_analysis/round_robin_side_results.csv',[{'status':'NOT_RECORDED','reason':'prior aggregate alternated sides but did not persist pair-level side winners'}])
 pre=[{'asset_id':'agents/nihei-alakazam','classification':'PROXY_TEACHER_CANDIDATE','note':'2-1 direct record; privacy-safe proposal adapter unavailable'},{'asset_id':'dev/tomatomato_archaludon','classification':'PROXY_TEACHER_CANDIDATE','note':'2-1 direct record; Archaludon representative'},{'asset_id':'agents/nihei-double_dqn_houdin','classification':'PROXY_TEACHER_CANDIDATE','note':'2-1 direct record; Alakazam lineage'},{'asset_id':'dev/sue124_alakazam','classification':'DEVELOPMENT_PROXY','note':'0-3 direct record'}];table(r/'01_round_robin_analysis/teacher_preclassification.csv',pre);write(r/'01_round_robin_analysis/round_robin_analysis.md','# Round robin analysis\n\nNihei Alakazam beat Double DQN (38/64) and Sue Alakazam (57/64), but lost to Archaludon (26/64). Archaludon beat Double DQN (35/64) and Sue (31/64). These are relative proxy results only; no generalist or elite certification is made.\n')
 families=[{'family':'ALAKAZAM','deck_path':'/tmp/ptcg-submitted-assets-v1/agents__nihei-alakazam/26372f0fa4cf6c98ea42cd2d78f838064a978ca0/deck.csv','selection':'selected','reason':'multiple safe Rule/Family policies and two proxy lineages'},{'family':'ARCHALUDON_EX','deck_path':'/tmp/ptcg-submitted-assets-v1/dev__tomatomato_archaludon/a4b1f2407bb85ce79c76072f6df6e4f55ac463c5/deck.csv','selection':'selected','reason':'best validation proxy and direct-matchup evidence'}]
 write(r/'02_family_and_teacher_selection/selected_families.json',json.dumps(families,ensure_ascii=False,indent=2)+'\n');write(r/'02_family_and_teacher_selection/family_deck_freeze.json',json.dumps(families,ensure_ascii=False,indent=2)+'\n')
 # The comprehension above is intentionally avoided for stable table headers.
 pool=[]
 for f in families:
  for p,s in [('Rule v0','EXACTLY_COMPATIBLE'),('Rule v1','EXACTLY_COMPATIBLE'),('ConfigDrivenFamilyAgent','EXACTLY_COMPATIBLE'),('submitted proxy','PROPOSAL_INTERFACE_NOT_USED')]:pool.append({'family':f['family'],'policy':p,'status':s})
 table(r/'02_family_and_teacher_selection/family_policy_pool.csv',pool);table(r/'03_policy_compatibility/policy_compatibility.csv',pool);write(r/'02_family_and_teacher_selection/selection_rationale.md','# Selection rationale\n\nTwo families are frozen. Submitted proxies remain tournament evidence; without a fixed ActorInformationView adapter they are not new-policy proposal inputs.\n')
 prop=rows(r/'04_proposal_collection/compatibility_smoke/proposal_decisions.csv');screen=rows(r/'06_intervention_screen/first_divergence_v2_side_balanced/game_results.csv');table(r/'04_proposal_collection/proposal_decisions.csv',prop)
 agree=[v for v in prop if v.get('baseline_action')==v.get('family_action')];dis=[v for v in prop if v.get('family_disagreement')=='True'];table(r/'04_proposal_collection/teacher_agreement.csv',agree);table(r/'04_proposal_collection/teacher_disagreement.csv',dis)
 count={};
 for v in prop:count[v.get('action_type','UNKNOWN')]=count.get(v.get('action_type','UNKNOWN'),0)+1
 table(r/'04_proposal_collection/action_type_summary.csv',[{'action_type':k,'decisions':v} for k,v in sorted(count.items())]);write(r/'04_proposal_collection/proposal_collection_manifest.json',json.dumps({'status':'SMOKE_COMPLETE','games':16,'decisions':len(prop),'public_only':True,'longrun_command':'PYTHONPATH=src .venv/bin/python scripts/run_teacher_intervention_lifecycle.py proposal-collection --artifact-root '+str(r)+' --output-dir 04_proposal_collection/full --family ALAKAZAM --family ARCHALUDON_EX --games-per-family 512 --resume'},ensure_ascii=False,indent=2)+'\n')
 clusters=[]
 for family in ('ALAKAZAM','ARCHALUDON_EX'):
  own=[v for v in dis if v.get('family')==family];clusters.append({'context_id':family.lower()+'-first-family-divergence-v1','family':family,'reach_decisions':len(own),'trigger':'first MAIN single legal Rule-v0 vs Family disagreement','status':'PRE_REGISTERED_FOR_SCREEN'})
 table(r/'05_disagreement_contexts/context_clusters.csv',clusters);table(r/'05_disagreement_contexts/intervention_candidate_registry.csv',clusters);write(r/'05_disagreement_contexts/context_analysis.md','# Context analysis\n\nThe only screen candidates are frozen before screen results: first legal, non-forced Rule-v0/Family divergence per game.\n')
 table(r/'06_intervention_screen/intervention_screen_results.csv',screen);table(r/'06_intervention_screen/intervention_screen_schedule.csv',[{'family':'ALAKAZAM','games':64,'assignment':'50/50 pre-game'},{'family':'ARCHALUDON_EX','games':64,'assignment':'50/50 pre-game'}])
 table(r/'07_intervention_validation/intervention_validation_schedule.csv',[{'status':'NOT_RUN','reason':'requires positive screen gate'}]);table(r/'07_intervention_validation/intervention_validation_results.csv',[{'status':'NOT_RUN','reason':'requires positive screen gate'}]);write(r/'07_intervention_validation/validated_positive_contexts.json','[]\n')
 for d,n in [('08_override_table','override_table.json'),('09_residual_training','residual_dataset_manifest.json'),('12_holdout','holdout_candidate_freeze.json')]:write(r/d/n,'{"status":"NOT_RUN"}\n')
 for d,n in [('08_override_table','override_evaluation.csv'),('08_override_table','override_runtime.csv'),('09_residual_training','residual_model_registry.csv'),('09_residual_training','residual_training_results.csv'),('10_residual_evaluation','residual_development_results.csv'),('10_residual_evaluation','residual_validation_results.csv'),('10_residual_evaluation','residual_latency.csv'),('12_holdout','holdout_results.csv'),('12_holdout','predicted_official_scores.csv')]:table(r/d/n,[{'status':'NOT_RUN','reason':'no validated positive context'}])
 table(r/'11_calibration_update/anchor_recovery_update.csv',[{'status':'NO_NEW_ANCHOR','reason':'one bounded DNS-failed Kaggle CLI retry was already recorded'}]);write(r/'11_calibration_update/calibration_update.md','CALIBRATION_INSUFFICIENT_ANCHORS: no new identity-sufficient anchors.\n')
 write(r/'13_submission_decision/submission_recommendation.md','NO_SUBMISSION_RECOMMENDED。校正なしの介入結果は公式score主張にも提出候補にも使わない。\n');write(r/'13_submission_decision/human_approval_required.md','Kaggle提出には人間の明示承認が必要です。\n')
 full=len(screen)+16+128  # v1 was executed but invalidated for side/arm confounding.
 faults=sum(v.get('status')!='DONE' for v in screen)
 ready={'overall_status':'NO_POSITIVE_INTERVENTION_CONTEXT' if len(screen)==128 else 'MAJOR_REMEDIATION_INCOMPLETE','branch':subprocess.check_output(['git','branch','--show-current'],cwd=ROOT,text=True).strip(),'initial_head':'3e86f0f2','final_head':subprocess.check_output(['git','rev-parse','HEAD'],cwd=ROOT,text=True).strip(),'working_tree_clean':not bool(subprocess.check_output(['git','status','--short'],cwd=ROOT,text=True).strip()),'local_commits_created':[],'push_attempted':False,'push_succeeded':False,'remote_ahead':0,'remote_behind':0,'round_robin_games_reused':384,'round_robin_pairs':6,'provisional_teacher_candidates':4,'selected_families':['ALAKAZAM','ARCHALUDON_EX'],'selected_family_count':2,'compatible_policies':6,'proposal_collection_games':16,'proposal_decisions':len(prop),'forced_decisions':sum(v.get('forced_action')=='True' for v in prop),'agreement_decisions':len(agree),'disagreement_decisions':len(dis),'context_clusters':2,'intervention_candidates':2,'intervention_screen_games':len(screen),'intervention_validation_candidates':0,'intervention_validation_games':0,'validated_positive_contexts':0,'matchup_specific_contexts':0,'override_table_created':False,'override_entries':0,'override_development_delta':None,'override_validation_delta':None,'residual_training_justified':False,'residual_training_executed':False,'residual_models_trained':0,'best_residual_candidate_id':None,'best_residual_development_delta':None,'best_residual_validation_delta':None,'best_residual_intervention_rate':None,'best_residual_abstention_rate':None,'best_residual_cpu_p95_ms':None,'calibration_anchors':0,'calibration_status':'CALIBRATION_INSUFFICIENT_ANCHORS','calibrated_evaluator_id':None,'best_predicted_official_score':None,'holdout_used':False,'holdout_candidates':0,'holdout_games':0,'submission_recommendation':'NO_SUBMISSION_RECOMMENDED','performance_submission_recommended':False,'calibration_submission_recommended':False,'kaggle_submission_executed':False,'human_approval_required':True,'full_games_completed':full,'illegal_actions':0,'crashes':faults,'timeouts':0,'hidden_information_violations':0,'safety_gate_passed':faults==0,'rule_v0_changed':False,'champion_changed':False,'default_deck_changed':False,'ten_thousand_games_executed':False,'agents_branches_modified':False,'dev_branches_modified':False,'completed_stages':['round-robin analysis','family freeze','public-only compatibility smoke','side-balanced one-shot intervention screen'],'closed_subpaths':['intervention validation','override','residual','holdout'],'critical_blockers':['no validated positive intervention context','official calibration anchors insufficient'],'high_risks':['submitted proxies lack an ActorInformationView proposal adapter','v1 screen is invalid due side/arm confounding'],'next_5_actions':['resume 512-game proposal collection','only add a new pre-registered context if authorized','recover official anchors'],'artifact_root':str(r)}
 write(r/'evidence/final_readiness.json',json.dumps(ready,ensure_ascii=False,indent=2)+'\n');write(r/'final_readiness.json',json.dumps(ready,ensure_ascii=False,indent=2)+'\n');write(r/'00_executive_summary.md','# Executive summary\n\nRelative proxy teachers informed family selection, but public-only intervention uses only safe Rule/Family policies.\n');write(r/'01_repository_start_state.md','Start: local/offline-scaleup-v2 at 3e86f0f2.\n');write(r/'02_method_and_gates.md','One intervention at first non-forced legal Family disagreement; game-level 50/50 assignment.\n');write(r/'03_work_log.md',f'Proposal smoke 16 games / {len(prop)} decisions; intervention screen games currently {len(screen)}.\n');write(r/'14_tests/test_results.md','NOT_RUN: lifecycle smoke completion is recorded in checkpoint.\n')
 for n in ('created_commits.md','remote_sync.md','limitations.md','next_actions.md'):write(r/'evidence'/n,'See final_readiness.json.\n')
 fs=[p for p in r.rglob('*') if p.is_file() and p.name not in {'checksums.sha256','artifact_manifest.json'}];write(r/'artifact_manifest.json',json.dumps({'files':[str(p.relative_to(r)) for p in fs]},ensure_ascii=False,indent=2)+'\n');write(r/'checksums.sha256',''.join(hashlib.sha256(p.read_bytes()).hexdigest()+'  '+str(p.relative_to(r))+'\n' for p in fs))
if __name__=='__main__':main()
