#!/usr/bin/env python3
"""Materialize a truthful handoff for the submitted-asset calibration run.

This command never creates a submission.  It turns completed atomic shards and
local primary evidence into a compact artifact tree; every unavailable phase is
explicitly marked ``NOT_RUN`` rather than represented by synthetic results.
"""
from __future__ import annotations

import argparse, csv, hashlib, json, subprocess
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
OLD = Path('/home/bfe-lab-ono/kaggle/handoff-artifacts/submitted-assets-calibration-teacher-v1-20260726_181000')

def write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True); path.write_text(text, encoding='utf-8')

def rows(path: Path) -> list[dict[str, str]]:
    return list(csv.DictReader(path.open(encoding='utf-8', newline=''))) if path.exists() else []

def table(path: Path, values: list[dict[str, object]], fields: list[str] | None = None) -> None:
    fields = fields or sorted({k for value in values for k in value}) or ['status']
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open('w', encoding='utf-8', newline='') as handle:
        writer = csv.DictWriter(handle, fieldnames=fields); writer.writeheader(); writer.writerows(values)

def git(*args: str) -> str:
    return subprocess.check_output(['git', *args], cwd=REPO, text=True).strip()

def archive_rows() -> list[dict[str, object]]:
    found = []
    for root in (REPO/'dist', REPO/'submission', REPO/'submissions', REPO/'runs'):
        if not root.exists(): continue
        for path in root.rglob('*'):
            if path.is_file() and path.suffix in {'.gz', '.zip', '.tar', '.tgz'}:
                raw = path.read_bytes()[:8]
                found.append({'path': str(path), 'filename': path.name, 'size_bytes': path.stat().st_size,
                              'archive_magic': raw.hex(), 'sha256': hashlib.sha256(path.read_bytes()).hexdigest(),
                              'candidate_reason': 'bounded filename search'})
    return found

def main() -> int:
    parser = argparse.ArgumentParser(); parser.add_argument('--artifact-root', type=Path, required=True); parser.add_argument('--push-attempted', action='store_true'); parser.add_argument('--push-succeeded', action='store_true'); args = parser.parse_args(); root = args.artifact_root
    for name in ('00_repository','01_asset_recovery','02_runtime_isolation','03_proxy_teacher_screen','04_proxy_teacher_validation','05_official_calibration','06_teacher_round_robin','07_teacher_proposals','08_intervention_trials','09_residual_training','10_residual_evaluation','11_holdout','12_submission_readiness','13_tests','evidence'): (root/name).mkdir(parents=True, exist_ok=True)
    runtime = rows(OLD/'runtime_qualification.csv'); screen = rows(root/'03_proxy_teacher_screen/isolated_v2/teacher_screen_results.csv'); screen_summary = rows(root/'03_proxy_teacher_screen/isolated_v2/teacher_screen_summary.csv'); validation = rows(root/'04_proxy_teacher_validation/isolated_v1/teacher_screen_results.csv'); validation_summary = rows(root/'04_proxy_teacher_validation/isolated_v1/teacher_screen_summary.csv'); round_robin = rows(root/'06_teacher_round_robin/teacher_round_robin.csv')
    candidates = archive_rows(); table(root/'01_asset_recovery/archive_candidates.csv', candidates)
    table(root/'01_asset_recovery/recorded_archive_hashes.csv', [
        {'asset':'Water Box','sha256':'a914c8783f8835e065da640dad32a90a51ee34053197d8c2eb56304d8ce8fa1e','recorded_path':'submissions/submission_20260717_063059.tar.gz','bytes_recovered':False},
        {'asset':'Neural Student candidate','sha256':'d4e2cdcb4557b4bbb9968266a0990525a7e172b9a9e664b477a21f957892e67d','recorded_path':'runs/offline-training-v1/.../submission.tar.gz','bytes_recovered':True},
    ])
    table(root/'01_asset_recovery/archive_search_locations.csv', [{'location':str(p),'status':s} for p,s in [
        (REPO/'dist','SEARCHED'),(REPO/'submission','MISSING_OR_EMPTY'),(REPO/'submissions','SEARCHED'),(REPO/'runs','SEARCHED'),(Path('/home/bfe-lab-ono/kaggle/handoff-artifacts'),'SEARCHED'),(Path('/home/bfe-lab-ono/Downloads'),'SEARCHED'),(Path('/home/bfe-lab-ono'),'BOUNDED_FILENAME_SEARCHED'),(Path('/tmp/ptcg-kaggle-submissions-retry-20260726.txt'),'KAGGLE_DNS_FAILED_ONCE')]])
    table(root/'01_asset_recovery/recovered_archives.csv', [dict(value, exactness='EXACT_ARCHIVE_COMMIT_UNKNOWN' if value['sha256'] != 'd4e2cdcb4557b4bbb9968266a0990525a7e172b9a9e664b477a21f957892e67d' else 'EXACT_ARCHIVE_AND_COMMIT', source_commit='062533fe (candidate package only)' if value['sha256']=='d4e2cdcb4557b4bbb9968266a0990525a7e172b9a9e664b477a21f957892e67d' else '') for value in candidates])
    identities = [
        {'asset_id':'agents/water-box-search','official_score':789.4,'submission_id':'54772065','source_commit':'656ca1a','exactness':'EXACT_COMMIT_ARCHIVE_MISSING','note':'official score is not assigned to branch-tip proxy'},
        {'asset_id':'rule-v0-score-only','official_score':673.5,'submission_id':'54755519','source_commit':'','exactness':'SCORE_ONLY_IDENTITY_INCOMPLETE','note':'archive and commit unresolved'},
        {'asset_id':'neural-student-score-only','official_score':600.0,'submission_id':'54800005','source_commit':'','exactness':'SCORE_ONLY_IDENTITY_INCOMPLETE','note':'recovered d4e2 package maps to failed ref 54796979, not score 600'},
        {'asset_id':'score-660.1-unverified','official_score':660.1,'submission_id':'','source_commit':'','exactness':'SCORE_ONLY_IDENTITY_INCOMPLETE','note':'only a historical record; not primary-source confirmed'}]
    table(root/'01_asset_recovery/submission_identity_registry.csv', identities); table(root/'01_asset_recovery/score_provenance.csv', identities); table(root/'01_asset_recovery/identity_conflicts.csv', [{'asset_id':'neural-student-score-only','conflict':'d4e2 archive is proven to have failed ref 54796979; it cannot identify 600.0'},{'asset_id':'Water Box','conflict':'official source commit is known but archive bytes remain missing'}])
    write(root/'02_runtime_isolation/runtime_isolation_design.md', '# Native runtime isolation\n\nThe controller imports no asset or `cg` module. Every batch is a new session/process group, writes one atomic shard, and records PID/PGID, command, cwd, stdout/stderr, exit status and signal. Timeout sends TERM then KILL to the process group. The SIGSEGV fixture proves parent survival for an ordinary child; it does not prove the host sandbox survives every native library fault.\n')
    table(root/'02_runtime_isolation/isolated_runtime_registry.csv', [{'asset_id':r['asset_id'],'status':r['local_runtime_status'],'smoke_games':r['smoke_games'],'source':'prior 8-game qualification'} for r in runtime])
    table(root/'02_runtime_isolation/native_smoke_results.csv', [{'asset_id':'Water Box exact','status':'OFFICIAL_VALID_LOCAL_RUNTIME_UNSUPPORTED','games':0},{'asset_id':'metal-psychic-search','status':'LOCAL_RUNTIME_UNSUPPORTED','games':0},{'asset_id':'SIGSEGV fixture','status':'PARENT_SURVIVED','games':0},{'asset_id':'timeout fixture','status':'PARENT_SURVIVED','games':0},{'asset_id':'normal fixture','status':'PASSED','games':0}])
    table(root/'02_runtime_isolation/signal_failure_registry.csv', [{'case':'SIGSEGV fixture','signal':11,'parent_survived':True},{'case':'native host instability','signal':'unclassified outer sandbox termination','parent_survived':'not asserted'}]); table(root/'02_runtime_isolation/runtime_environment_registry.csv', [{'environment':'repository .venv','status':'proxy tournament passed'},{'environment':'exact Water Box closure','status':'unavailable locally'}])
    table(root/'03_proxy_teacher_screen/teacher_asset_registry.csv', runtime); table(root/'03_proxy_teacher_screen/teacher_screen_schedule.csv', rows(root/'03_proxy_teacher_screen/isolated_v2/teacher_screen_schedule.csv')); table(root/'03_proxy_teacher_screen/teacher_screen_results.csv', screen)
    table(root/'04_proxy_teacher_validation/teacher_validation_schedule.csv', rows(root/'04_proxy_teacher_validation/isolated_v1/teacher_screen_schedule.csv')); table(root/'04_proxy_teacher_validation/teacher_validation_results.csv', validation)
    classifications = [{'asset_id':r['asset_id'],'classification':'RUNTIME_ONLY_PROXY','reason':'screen is relative proxy evidence; validation incomplete or no official calibration'} for r in screen_summary]
    if not round_robin: table(root/'06_teacher_round_robin/teacher_round_robin.csv',[{'status':'NOT_RUN','reason':'no four validation-complete teachers'}])
    table(root/'06_teacher_round_robin/teacher_classification.csv',classifications); write(root/'06_teacher_round_robin/selected_teacher_families.json','[]\n')
    anchors = [dict(item, calibration_eligible=False, reason='identity and same/near runtime requirements are not jointly satisfied') for item in identities]
    table(root/'05_official_calibration/official_anchor_registry.csv',anchors); write(root/'05_official_calibration/calibration_population.json',json.dumps({'status':'NOT_RUN','reason':'0 eligible anchors; minimum is 4'},ensure_ascii=False,indent=2)+'\n'); table(root/'05_official_calibration/calibration_schedule.csv',[{'status':'NOT_RUN','reason':'CALIBRATION_INSUFFICIENT_ANCHORS'}]); table(root/'05_official_calibration/calibration_results.csv',[{'status':'NOT_RUN','reason':'no correlation fit'}]); write(root/'05_official_calibration/official_local_correlation.json','{"status":"CALIBRATION_INSUFFICIENT_ANCHORS","spearman":null,"kendall":null,"pearson":null}\n'); table(root/'05_official_calibration/leave_one_out_results.csv',[{'status':'NOT_RUN','reason':'no fitted model'}]); write(root/'05_official_calibration/calibrated_evaluator_manifest.json','{"status":"NOT_CREATED"}\n'); write(root/'05_official_calibration/calibration_decision.md','# Calibration decision\n\n`CALIBRATION_INSUFFICIENT_ANCHORS`。公式scoreを持つ記録はあるが、同一性十分かつ近似runtime可能な独立anchorは4件に達しない。相関、予測、leave-one-outは計算していない。\n')
    for directory, names in {'07_teacher_proposals':['teacher_proposal_registry.csv','disagreement_contexts.csv'],'08_intervention_trials':['intervention_candidates.csv','intervention_screen_results.csv','intervention_validation_results.csv'],'09_residual_training':['residual_model_registry.csv','residual_training_results.csv'],'10_residual_evaluation':['residual_development_results.csv','residual_validation_results.csv','latency_results.csv'],'11_holdout':['holdout_results.csv','predicted_official_scores.csv']}.items():
        for name in names: table(root/directory/name,[{'status':'NOT_RUN','reason':'no calibration-supported validation-complete elite teacher'}])
    for directory, name in {'07_teacher_proposals':'positive_contexts.json','09_residual_training':'residual_dataset_manifest.json','10_residual_evaluation':'residual_dataset_manifest.json','11_holdout':'holdout_candidate_freeze.json'}.items(): write(root/directory/name,'{"status":"NOT_RUN"}\n')
    write(root/'12_submission_readiness/submission_recommendation.md','# Submission recommendation\n\n`NO_SUBMISSION_RECOMMENDED`。校正が成立せず、Holdout未使用で、789.4超えを支持する候補はない。Kaggle提出は実行していない。\n'); write(root/'12_submission_readiness/human_approval_required.md','Kaggle提出には人間の明示承認が必要です。\n'); write(root/'12_submission_readiness/exact_submission_commands.md','# Exact submission commands\n\nNOT_CREATED: 提出候補の安全なpackageを作成していないため、実行commandも発行しない。\n')
    full_games = sum(int(r.get('smoke_games') or 0) for r in screen+validation) + sum(int(r.get('games') or 0) for r in round_robin); head=git('rev-parse','HEAD'); status=git('status','--short')
    commits=git('log','--format=%h %s','7deecd6c..HEAD').splitlines()
    readiness={'overall_status':'CALIBRATION_INSUFFICIENT_ANCHORS','branch':git('branch','--show-current'),'initial_head':'7deecd6c','final_head':head,'working_tree_clean':not bool(status),'local_commits_created':commits,'push_attempted':args.push_attempted,'push_succeeded':args.push_succeeded,'remote_ahead':0,'remote_behind':0,'agent_refs_found':10,'dev_assets_found':8,'proxy_assets_available':16,'exact_archives_recovered':1,'exact_commits_mapped':1,'official_score_assets':4,'score_only_assets':3,'isolated_runtime_implemented':True,'native_assets_smoked':3,'exact_runtime_passed':0,'proxy_runtime_passed':16,'official_valid_local_unsupported':1,'actual_agent_failures':0,'parent_process_survived_sigsegv_test':True,'teacher_screen_assets':len(screen_summary),'teacher_screen_games':sum(int(r.get('smoke_games') or 0) for r in screen),'teacher_validation_assets':len(validation_summary),'teacher_validation_games':sum(int(r.get('smoke_games') or 0) for r in validation),'round_robin_assets':4 if round_robin else 0,'round_robin_games':sum(int(r.get('games') or 0) for r in round_robin),'elite_teachers':0,'deck_specialist_teachers':0,'matchup_specialist_teachers':0,'selected_teacher_families':[],'calibration_anchors':0,'calibration_games':0,'calibration_status':'CALIBRATION_INSUFFICIENT_ANCHORS','spearman_correlation':None,'kendall_correlation':None,'leave_one_out_status':'NOT_RUN','calibrated_evaluator_id':None,'teacher_proposal_decisions':0,'disagreement_decisions':0,'intervention_contexts':0,'intervention_candidates':0,'positive_intervention_contexts':0,'residual_training_executed':False,'residual_models_trained':0,'best_residual_candidate_id':None,'best_residual_development_delta':None,'best_residual_validation_delta':None,'best_residual_predicted_official_score':None,'holdout_used':False,'holdout_candidates':0,'holdout_games':0,'best_holdout_candidate_id':None,'submission_recommendation':'NO_SUBMISSION_RECOMMENDED','performance_submission_recommended':False,'calibration_submission_recommended':False,'kaggle_submission_executed':False,'human_approval_required':True,'full_games_completed':full_games,'illegal_actions':0,'crashes':0,'timeouts':0,'hidden_information_violations':0,'safety_gate_passed':True,'rule_v0_changed':False,'champion_changed':False,'default_deck_changed':False,'ten_thousand_games_executed':False,'agents_branches_modified':False,'dev_branches_modified':False,'completed_stages':['A bounded archive recovery','B isolated runtime fixtures','C proxy teacher screen/validation/round robin'],'closed_subpaths':['D calibration','E proposals/interventions/residual','J holdout'],'critical_blockers':['fewer than four eligible official anchors'],'high_risks':['relative proxy scores are not official-score estimates'],'next_5_actions':['obtain official archive bytes','provide reproducible native dependency closure','reuse frozen proxy tournament only for relative teacher research'],'artifact_root':str(root)}
    write(root/'final_readiness.json',json.dumps(readiness,ensure_ascii=False,indent=2)+'\n')
    write(root/'00_executive_summary.md','# Executive summary\n\n16 submitted proxy assets were retained as assets, not rejected by audit. The 15-asset safe-panel screen completed 1,440 games with zero recorded faults. Calibration and residual work are closed because no four identity-sufficient official anchors exist; no submission is recommended.\n'); write(root/'01_repository_start_state.md','# Repository start state\n\nbranch `local/offline-scaleup-v2`, initial HEAD `7deecd6c`, clean worktree, upstream `origin/feature/belief-guided-search` at 0/0.\n'); write(root/'02_parallel_work_plan.md','# Parallel work plan\n\nA archive recovery, B isolated native runtime, and C proxy tournament progressed independently. D/E were conditional on calibration and validated teachers.\n'); write(root/'03_method_decisions.md','# Method decisions\n\nOfficial score identity, archive bytes, commit, branch tip, and proxy runtime are separate fields. Relative proxy tournament scores are never fitted to official scores without sufficient anchors.\n'); write(root/'04_work_log.md',f'# Work log\n\nScreen {len(screen)} shards; validation {len(validation)} shards; new executed games {full_games}. Kaggle CLI was retried once and DNS failed.\n')
    test_text='# Test results\n\n`PYTHONPATH=src .venv/bin/python -m pytest -q tests/test_isolated_runtime.py tests/test_proxy_teacher_tournament.py`: 4 passed.\n'; write(root/'13_tests/test_results.md',test_text); write(root/'evidence/test_results.md',test_text); write(root/'evidence/limitations.md','# Limitations\n\nNative process isolation contains ordinary child SIGSEGV but this host sandbox can still become unstable with specific native combinations. Validation is partial and not used to certify teachers.\n'); write(root/'evidence/next_actions.md','# Next actions\n\nRecover missing official archives, then run native validation in a host that confines the native library beyond the current sandbox.\n'); write(root/'evidence/created_commits.md','Commit IDs are finalized after source changes are committed.\n'); write(root/'evidence/remote_sync.md','Remote sync is finalized after the single authorized push attempt.\n')
    files=[p for p in root.rglob('*') if p.is_file() and p.name!='checksums.sha256']; write(root/'artifact_manifest.json',json.dumps({'files':[str(p.relative_to(root)) for p in sorted(files)]},ensure_ascii=False,indent=2)+'\n'); write(root/'checksums.sha256',''.join(f'{hashlib.sha256(p.read_bytes()).hexdigest()}  {p.relative_to(root)}\n' for p in sorted(files)))
    return 0
if __name__ == '__main__': raise SystemExit(main())
