#!/usr/bin/env python3
"""公開 leaderboard 分析から、学習プールに無い medal 圏デッキを相手として追加する。

## なぜ必要か

一様巡回の学習プールは実際のラダー分布から大きくずれていた。medal 圏 (金銀銅) の
37% を占める Marnie's Grimmsnarl ex にプールの 6.7% しか割かれず、逆に medal 圏
1.6% の Mega Lucario ex にプールの 15% を割いていた。medal 圏 62 件のうち手元の
デッキでカバーできるのは 33 件 (53%) だけで、金 3 件を占める Mega Lopunny ex は
1 体も無い (docs/evidence/vtrace-rl-degrades-against-eval-pool-20260807.md)。

## 何を作るか

`opponents/medal_<rank>_<hash8>/` に `deck.csv` / `main.py` / `SOURCE.md` を書き、
`pool_manifest.json` へ登録する。既存の `opponents/meta_*` と同じ方式である。

- **decklist だけ**が公開リプレイ由来。操縦は `agents.generic_agent` の deck 非依存
  rule policy で、元チームの agent や戦略とは無関係である。したがってこれらを
  「leaderboard team の再現」と呼んではならない (正典 §13, §2.2)。
- `usage_boundary` は `local_eval_only`。提出 bundle へ入れない。

## 評価プールは触らない

held-out の 6 体は学習にも使わず、この生成器も追加しない。評価基準が動くと過去の
測定と比較できなくなる。
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from collections import Counter
from pathlib import Path

_ROOT = Path(__file__).resolve().parents[1]
sys.path[:0] = [str(_ROOT), str(_ROOT / "src")]

EVAL_HELD_OUT_V1 = (
    "kiyotah_lucario", "sue124_alakazam", "skarin_dragapult",
    "ozawa_crustle_v2", "nihei_megalopunny", "yaroslav_crustleaware_lucario",
)

_MAIN_TEMPLATE_V1 = '''"""Auto-generated medal-zone opponent (scripts/make_medal_opponents.py) -- DO NOT
EDIT BY HAND (re-run the generator instead; see SOURCE.md for provenance).

Deck: taken from a public Kaggle "PTCG AI Battle" replay's initial visualizer
state, via report/leaderboard-deck-analysis-*.json. The agent piloting it is
NOT taken from anywhere: it is agents.generic_agent's deck-agnostic rule-based
policy, loaded with this directory's deck.csv. Only the decklist comes from the
replay, never the play.

NOT SUBMITTABLE TO KAGGLE AS-IS: this main.py imports agents.generic_agent from
the repository, which is not part of a Kaggle submission bundle. It is a
local-bench-only opponent (see SOURCE.md).
"""

import os

from agents.generic_agent import make_agent


def _read_deck():
    path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "deck.csv")
    with open(path, "r", encoding="utf-8") as fh:
        lines = [line for line in fh.read().splitlines() if line.strip()]
    return [int(lines[i]) for i in range(60)]


agent = make_agent(_read_deck())
'''

_SOURCE_TEMPLATE_V1 = """# Source

- Generated by: `scripts/make_medal_opponents.py`
- Source analysis: `{analysis}` (snapshot {snapshot})
- Competition: `{competition}`
- deck_sha256: `{deck_hash}`
- medal 圏での観測: {tier_summary}
- 観測順位: {ranks}
- アーキタイプ (主軸ポケモン): {archetype}

## Usage note

この decklist は公開 Kaggle リプレイの初期 visualizer state から取得したもので、
手書きのデッキではない。操縦は `agents.generic_agent` (deck 非依存の rule-based
policy、`opponents/meta_*` と共有) であり、元エピソードの agent や戦略とは無関係
である。**meta 由来なのは decklist だけで、プレイではない。**

したがってこの相手を「leaderboard team の再現」と呼んではならない。

**local-bench 専用で、そのままでは Kaggle へ提出できない**: `main.py` が repository の
`agents.generic_agent` を import しており、これは提出 bundle に含まれない。
"""


def _deck_hash(deck: list[int]) -> str:
    payload = ",".join(str(card) for card in sorted(deck)).encode("utf-8")
    return hashlib.sha256(payload).hexdigest()


def _archetype(deck: list[int]) -> str:
    from cg.api import all_card_data

    cards = {card.cardId: card for card in all_card_data()}
    mons = []
    for card_id in set(deck):
        card = cards.get(card_id)
        if card is None or card.hp <= 0:
            continue
        mons.append(((card.megaEx or card.ex, card.stage2, card.stage1, card.hp), card.name))
    mons.sort(reverse=True)
    return " / ".join(name for _rank, name in mons[:2]) or "(unknown)"


def _existing_decks(opponents_dir: Path) -> dict[tuple[int, ...], str]:
    found: dict[tuple[int, ...], str] = {}
    for entry in sorted(opponents_dir.iterdir()):
        deck_path = entry / "deck.csv"
        if not entry.is_dir() or not deck_path.is_file():
            continue
        ids = [line.strip() for line in deck_path.read_text().splitlines() if line.strip()]
        if len(ids) == 60:
            found.setdefault(tuple(sorted(int(x) for x in ids)), entry.name)
    return found


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--analysis", required=True,
                        help="report/leaderboard-deck-analysis-*.json のパス")
    parser.add_argument("--opponents-dir", default=str(_ROOT / "opponents"))
    parser.add_argument("--include-rivals", action="store_true",
                        help="medal 圏に加え、中位ライバル層のデッキも取り込む")
    parser.add_argument("--apply", action="store_true",
                        help="指定しなければ何も書かず、追加候補だけを表示する")
    args = parser.parse_args()

    analysis_path = Path(args.analysis)
    analysis = json.loads(analysis_path.read_text(encoding="utf-8"))
    opponents_dir = Path(args.opponents_dir)
    existing = _existing_decks(opponents_dir)

    sources = ["gold", "silver", "bronze"]
    rows = []
    for tier in sources:
        for entry in analysis["medal_tiers"][tier]:
            rows.append((tier, entry["rank"], entry["deck"]))
    if args.include_rivals:
        for entry in analysis["rivals"]:
            rows.append(("rivals", entry["rank"], entry["deck"]))

    grouped: dict[tuple[int, ...], list[tuple[str, int]]] = {}
    for tier, rank, deck in rows:
        grouped.setdefault(tuple(sorted(int(c) for c in deck)), []).append((tier, rank))

    planned = []
    for key, seen in sorted(grouped.items(), key=lambda kv: (-len(kv[1]), min(r for _t, r in kv[1]))):
        if key in existing:
            continue
        best_rank = min(rank for _tier, rank in seen)
        digest = _deck_hash(list(key))
        planned.append((f"medal_{best_rank:04d}_{digest[:8]}", list(key), seen, digest))

    print(f"medal 圏{'+中位層' if args.include_rivals else ''} の異なるデッキ {len(grouped)} 種 / "
          f"既に手元にある {len(grouped) - len(planned)} 種 / 追加候補 {len(planned)} 種")
    for name, deck, seen, _digest in planned:
        tiers = Counter(tier for tier, _rank in seen)
        print(f"  {name:<24} {len(seen):>2}件 {dict(tiers)}  {_archetype(deck)[:44]}")

    if not args.apply:
        print("\n--apply を付けると書き込みます。")
        return 0

    manifest_path = opponents_dir / "pool_manifest.json"
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    known = {row["id"] for row in manifest}

    written = 0
    for name, deck, seen, digest in planned:
        target = opponents_dir / name
        target.mkdir(parents=True, exist_ok=True)
        (target / "deck.csv").write_text(
            "\n".join(str(card) for card in deck) + "\n", encoding="utf-8")
        (target / "main.py").write_text(_MAIN_TEMPLATE_V1, encoding="utf-8")
        tiers = Counter(tier for tier, _rank in seen)
        (target / "SOURCE.md").write_text(_SOURCE_TEMPLATE_V1.format(
            analysis=analysis_path.name,
            snapshot=analysis.get("snapshot_utc", "unknown"),
            competition=analysis.get("competition", "unknown"),
            deck_hash=digest,
            tier_summary=", ".join(f"{k} {v}件" for k, v in sorted(tiers.items())),
            ranks=", ".join(str(rank) for _tier, rank in sorted(seen, key=lambda x: x[1])),
            archetype=_archetype(deck),
        ), encoding="utf-8")
        if name not in known:
            manifest.append({
                "canonical_deck_hash": digest,
                "id": name,
                "mean_decision_ms": None,
                "policy_hash": hashlib.sha256(
                    (target / "main.py").read_bytes()).hexdigest(),
                "smoke_ok": False,   # 実測するまで真にしない
                "source": "public",
                "usage_boundary": "local_eval_only",
            })
        written += 1

    manifest.sort(key=lambda row: row["id"])
    manifest_path.write_text(
        json.dumps(manifest, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"\n{written} 体を書き出し、pool_manifest.json を更新した "
          f"(合計 {len(manifest)} 体)。smoke_ok は実測まで false のままである。")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
