"""Tests for offline_reader.py + phase.py + replay_normalize.py.

Fixtures are generated by calling the *real* Offline Training v1 collector
(``run_collection(source="fixture", ...)``) exactly like
``tests/test_offline_training_v1.py`` does, rather than hand-authoring JSON:
the real writer's hashing/redaction/manifest logic is nontrivial to fake
correctly by hand, and this proves the O1-2 reader against the actual
on-disk contract, not a guess at it. This never touches the actual cabt
engine (``source="fixture"`` drives a deterministic synthetic match runner).
"""

from __future__ import annotations

import gzip
import json
from pathlib import Path

import pytest

from mage_ptcg.competition_intelligence.offline_reader import (
    RuleBCRowError,
    discover_offline_training_run,
    iter_rule_bc_rows,
    parse_rule_bc_row,
)
from mage_ptcg.competition_intelligence.phase import (
    BOARD_DEVELOPMENT,
    ENDGAME,
    FIRST_MAJOR_EXCHANGE,
    OPENING,
    PRIZE_RACE,
    SETUP,
    UNKNOWN,
    classify_phase,
)
from mage_ptcg.competition_intelligence.replay_normalize import normalize_rule_bc_jsonl

REPO_ROOT = Path(__file__).resolve().parents[2]
DECK_PATH = REPO_ROOT / "deck.csv"


@pytest.fixture(scope="module")
def collected_run(tmp_path_factory) -> Path:
    from mage_ptcg.offline_training.collection import run_collection

    root = tmp_path_factory.mktemp("o1-2-collection")
    # Match the real production layout: the full Offline Training v1 CLI
    # pipeline (Pipeline.phase_collect) passes output_root=<run>/"collection",
    # not the run root directly -- run_collection() itself has no opinion on
    # this extra directory layer, so a faithful "existing run artifact"
    # fixture must add it explicitly.
    run_collection(
        source="fixture",
        run_id="cabt",
        games=6,
        base_seed=1000,
        output_root=root / "collection",
        canonical_base_sha="a" * 40,
        deck_path=DECK_PATH,
        repository_root=REPO_ROOT,
        validation_percent=20,
        split_seed=0,
        fixture_decisions_per_seat=4,
        fixture_option_count=3,
    )
    return root


@pytest.fixture(scope="module")
def rule_bc_jsonl_path(collected_run: Path) -> Path:
    return collected_run / "collection" / "cabt" / "private_dataset" / "rule-bc-v1.jsonl"


class TestDiscoverOfflineTrainingRun:
    def test_discovers_real_collection_output(self, collected_run: Path) -> None:
        discovered = discover_offline_training_run(collected_run)
        assert discovered.is_usable()
        assert discovered.collection_jsonl_path is not None
        assert discovered.collection_jsonl_path.name == "rule-bc-v1.jsonl"
        assert discovered.collection_bindings_path is not None
        assert discovered.dataset_manifest_path is None  # build-dataset phase not run in this fixture

    def test_missing_run_root_reports_not_usable(self, tmp_path: Path) -> None:
        discovered = discover_offline_training_run(tmp_path / "does-not-exist")
        assert not discovered.is_usable()
        assert discovered.collection_jsonl_path is None

    def test_discovers_direct_collector_output_without_collection_subdir(self, tmp_path_factory) -> None:
        from mage_ptcg.offline_training.collection import run_collection

        root = tmp_path_factory.mktemp("o1-2-direct-collection")
        run_collection(
            source="fixture", run_id="cabt", games=2, base_seed=2000, output_root=root,
            canonical_base_sha="a" * 40, deck_path=DECK_PATH, repository_root=REPO_ROOT,
            validation_percent=20, split_seed=0, fixture_decisions_per_seat=2, fixture_option_count=3,
        )
        discovered = discover_offline_training_run(root)
        assert discovered.is_usable()
        assert discovered.collection_jsonl_path == root / "cabt" / "private_dataset" / "rule-bc-v1.jsonl"

    def test_never_writes_anything_under_source_run(self, collected_run: Path) -> None:
        before = sorted(p for p in collected_run.rglob("*") if p.is_file())
        discover_offline_training_run(collected_run)
        after = sorted(p for p in collected_run.rglob("*") if p.is_file())
        assert before == after


class TestIterRuleBcRows:
    def test_reads_real_rows(self, rule_bc_jsonl_path: Path) -> None:
        rows = list(iter_rule_bc_rows(rule_bc_jsonl_path))
        assert len(rows) > 0
        assert all(error is None for _, _, error in rows)
        assert all(row is not None and row["schema_version"] == "rule-bc-v1" for _, row, _ in rows)

    def test_gzip_variant_is_transparent(self, rule_bc_jsonl_path: Path, tmp_path: Path) -> None:
        gz_path = tmp_path / "rule-bc-v1.jsonl.gz"
        with gzip.open(gz_path, "wt", encoding="utf-8") as handle:
            handle.write(rule_bc_jsonl_path.read_text(encoding="utf-8"))
        plain_rows = [row for _, row, _ in iter_rule_bc_rows(rule_bc_jsonl_path)]
        gz_rows = [row for _, row, _ in iter_rule_bc_rows(gz_path)]
        assert plain_rows == gz_rows

    def test_malformed_json_line_is_quarantined_not_fatal(self, tmp_path: Path) -> None:
        path = tmp_path / "broken.jsonl"
        path.write_text('{"not": "closed"\n{"schema_version": "rule-bc-v1"}\n', encoding="utf-8")
        results = list(iter_rule_bc_rows(path))
        assert len(results) == 2
        assert results[0][1] is None and results[0][2] is not None
        assert results[1][1] is None and results[1][2] is not None  # missing required keys

    def test_truncated_final_line_is_quarantined(self, rule_bc_jsonl_path: Path, tmp_path: Path) -> None:
        original = rule_bc_jsonl_path.read_text(encoding="utf-8")
        truncated_path = tmp_path / "truncated.jsonl"
        truncated_path.write_text(original + '{"schema_version": "rule-bc-v1", "truncat', encoding="utf-8")
        results = list(iter_rule_bc_rows(truncated_path))
        assert results[-1][1] is None
        assert results[-1][2] is not None

    def test_empty_lines_are_skipped(self, tmp_path: Path) -> None:
        path = tmp_path / "with_blanks.jsonl"
        path.write_text("\n\n", encoding="utf-8")
        assert list(iter_rule_bc_rows(path)) == []


class TestParseRuleBcRow:
    def test_rejects_non_object(self) -> None:
        with pytest.raises(RuleBCRowError):
            parse_rule_bc_row([1, 2, 3])

    def test_rejects_wrong_schema_version(self) -> None:
        with pytest.raises(RuleBCRowError):
            parse_rule_bc_row({"schema_version": "wrong-v0"})

    def test_rejects_missing_metadata_keys(self, rule_bc_jsonl_path: Path) -> None:
        _, row, _ = next(iter(iter_rule_bc_rows(rule_bc_jsonl_path)))
        assert row is not None
        broken = dict(row)
        broken["metadata"] = {k: v for k, v in row["metadata"].items() if k != "seat"}
        with pytest.raises(RuleBCRowError):
            parse_rule_bc_row(broken)

    def test_rejects_malformed_legal_actions(self, rule_bc_jsonl_path: Path) -> None:
        _, row, _ = next(iter(iter_rule_bc_rows(rule_bc_jsonl_path)))
        assert row is not None
        broken = dict(row)
        broken["legal_actions"] = [{"no_digest_key": True}]
        with pytest.raises(RuleBCRowError):
            parse_rule_bc_row(broken)


class TestPhaseClassification:
    def test_termination_proximate_is_endgame(self) -> None:
        result = classify_phase(
            turn=5, self_prize_count=4, opponent_prize_count=4,
            self_active_present=True, opponent_active_present=True, termination_proximate=True,
        )
        assert result.phase == ENDGAME
        assert "termination" in result.reason

    def test_low_prize_count_is_endgame(self) -> None:
        result = classify_phase(
            turn=10, self_prize_count=1, opponent_prize_count=3,
            self_active_present=True, opponent_active_present=True,
        )
        assert result.phase == ENDGAME

    def test_half_prizes_taken_is_prize_race(self) -> None:
        result = classify_phase(
            turn=8, self_prize_count=3, opponent_prize_count=5,
            self_active_present=True, opponent_active_present=True,
        )
        assert result.phase == PRIZE_RACE

    def test_first_prize_taken_is_first_major_exchange(self) -> None:
        result = classify_phase(
            turn=5, self_prize_count=5, opponent_prize_count=6,
            self_active_present=True, opponent_active_present=True,
        )
        assert result.phase == FIRST_MAJOR_EXCHANGE

    def test_turn_zero_is_opening(self) -> None:
        result = classify_phase(
            turn=0, self_prize_count=6, opponent_prize_count=6,
            self_active_present=None, opponent_active_present=None,
        )
        assert result.phase == OPENING

    def test_no_active_pokemon_is_setup(self) -> None:
        result = classify_phase(
            turn=2, self_prize_count=6, opponent_prize_count=6,
            self_active_present=False, opponent_active_present=True,
        )
        assert result.phase == SETUP

    def test_early_turn_both_active_is_board_development(self) -> None:
        result = classify_phase(
            turn=3, self_prize_count=6, opponent_prize_count=6,
            self_active_present=True, opponent_active_present=True,
        )
        assert result.phase == BOARD_DEVELOPMENT

    def test_missing_turn_and_prizes_is_unknown(self) -> None:
        result = classify_phase(
            turn=None, self_prize_count=None, opponent_prize_count=None,
            self_active_present=None, opponent_active_present=None,
        )
        assert result.phase == UNKNOWN
        assert "unavailable" in result.reason

    def test_every_result_carries_reason_and_evidence(self) -> None:
        result = classify_phase(
            turn=4, self_prize_count=6, opponent_prize_count=6,
            self_active_present=True, opponent_active_present=True,
        )
        assert result.reason
        assert "turn" in result.evidence

    def test_rejects_invalid_phase_construction(self) -> None:
        from mage_ptcg.competition_intelligence.phase import PhaseClassification

        with pytest.raises(ValueError):
            PhaseClassification("NOT_A_PHASE", "reason", {})


class TestNormalizeRuleBcJsonl:
    def test_produces_episodes_and_decisions(self, rule_bc_jsonl_path: Path) -> None:
        result = normalize_rule_bc_jsonl(rule_bc_jsonl_path, source_id="local:test-source")
        assert result.source_row_count > 0
        assert result.valid_row_count == result.source_row_count
        assert len(result.quarantined_rows) == 0
        assert len(result.episodes) == 6  # games=6 in the fixture
        assert len(result.decisions) > 0

    def test_episode_source_id_is_the_envelope_id_not_the_episode_id(self, rule_bc_jsonl_path: Path) -> None:
        result = normalize_rule_bc_jsonl(rule_bc_jsonl_path, source_id="local:envelope-42")
        for episode in result.episodes:
            assert episode.source_id == "local:envelope-42"
            assert episode.episode_id != "local:envelope-42"

    def test_raw_row_source_id_key_is_pinned_to_mean_episode_identity(self, rule_bc_jsonl_path: Path) -> None:
        # Independent-audit finding #5 (schema naming collision, minimal-fix
        # scope): a raw rule-bc-v1 row's own "source_id" key is NOT a
        # contracts.SourceEnvelope id -- it holds the row's *episode*
        # identity, unrelated to this function's own `source_id` keyword
        # argument (the actual envelope id, checked in the test above). This
        # test pins that specific mapping so a future schema change would
        # have to break it visibly, not silently.
        raw_row_source_ids = {row["source_id"] for _, row, _ in iter_rule_bc_rows(rule_bc_jsonl_path) if row is not None}
        result = normalize_rule_bc_jsonl(rule_bc_jsonl_path, source_id="local:envelope-42")
        normalized_episode_ids = {episode.episode_id for episode in result.episodes}
        assert raw_row_source_ids == normalized_episode_ids
        assert "local:envelope-42" not in raw_row_source_ids

    def test_decision_indices_are_ordered_within_episode(self, rule_bc_jsonl_path: Path) -> None:
        result = normalize_rule_bc_jsonl(rule_bc_jsonl_path, source_id="local:test-source")
        by_episode: dict[str, list[int]] = {}
        for decision in result.decisions:
            by_episode.setdefault(decision.episode_id, []).append(decision.decision_index)
        for indices in by_episode.values():
            assert indices == sorted(indices)
            assert len(indices) == len(set(indices))  # no duplicate decision_index within an episode

    def test_stable_action_key_digests_reused_verbatim(self, rule_bc_jsonl_path: Path) -> None:
        raw_digests: set[str] = set()
        for _, row, _ in iter_rule_bc_rows(rule_bc_jsonl_path):
            assert row is not None
            raw_digests.update(action["digest"] for action in row["legal_actions"])
        result = normalize_rule_bc_jsonl(rule_bc_jsonl_path, source_id="local:test-source")
        normalized_digests: set[str] = set()
        for decision in result.decisions:
            if decision.legal_action_keys:
                normalized_digests.update(decision.legal_action_keys)
        assert normalized_digests.issubset(raw_digests)
        assert normalized_digests  # non-empty: real reuse happened, not silently dropped

    def test_actor_information_view_never_contains_opponent_hand_cards(self, rule_bc_jsonl_path: Path) -> None:
        result = normalize_rule_bc_jsonl(rule_bc_jsonl_path, source_id="local:test-source")
        for decision in result.decisions:
            view = decision.actor_information_view
            assert view is not None
            public_state = view["public_state"]
            opponent = public_state.get("opponent", {})
            # opponent hand must only ever be a count, never a card list
            assert "hand" not in opponent or opponent.get("hand") == []

    def test_quality_flags_document_source_limitations(self, rule_bc_jsonl_path: Path) -> None:
        result = normalize_rule_bc_jsonl(rule_bc_jsonl_path, source_id="local:test-source")
        for episode in result.episodes:
            assert "winner_unavailable_in_source" in episode.quality_flags
            assert episode.winner is None

    def test_latency_and_result_to_go_are_none_not_fabricated(self, rule_bc_jsonl_path: Path) -> None:
        result = normalize_rule_bc_jsonl(rule_bc_jsonl_path, source_id="local:test-source")
        for decision in result.decisions:
            assert decision.latency_us is None
            assert decision.result_to_go is None

    def test_malformed_rows_are_quarantined_not_fatal(self, rule_bc_jsonl_path: Path, tmp_path: Path) -> None:
        original = rule_bc_jsonl_path.read_text(encoding="utf-8")
        broken_path = tmp_path / "broken.jsonl"
        broken_path.write_text(original + '{"schema_version": "rule-bc-v1"}\n', encoding="utf-8")
        result = normalize_rule_bc_jsonl(broken_path, source_id="local:test-source")
        assert len(result.quarantined_rows) == 1
        assert result.valid_row_count == result.source_row_count - 1

    def test_public_trace_hash_is_deterministic(self, rule_bc_jsonl_path: Path) -> None:
        first = normalize_rule_bc_jsonl(rule_bc_jsonl_path, source_id="local:test-source")
        second = normalize_rule_bc_jsonl(rule_bc_jsonl_path, source_id="local:test-source")
        first_hashes = {e.episode_id: e.public_trace_hash for e in first.episodes}
        second_hashes = {e.episode_id: e.public_trace_hash for e in second.episodes}
        assert first_hashes == second_hashes

    def test_first_player_extracted_when_available(self, rule_bc_jsonl_path: Path) -> None:
        result = normalize_rule_bc_jsonl(rule_bc_jsonl_path, source_id="local:test-source")
        assert any(episode.first_player is not None for episode in result.episodes)
