"""Render an independent deck-adaptive, public-state-only CG policy.

The renderer is intentionally not an overlay on the sealed P1 source.  It
creates a small generic policy from the generated deck's card IDs and the
official ``cg.api`` card metadata.  A caller may copy an existing verified
``cg/`` runtime into the resulting package, but the policy source itself is
generated by this module and never imports a historical policy.
"""

from __future__ import annotations

from dataclasses import dataclass, fields
import hashlib
import json
from pathlib import Path
import shutil
from typing import Mapping, Sequence

from .self_owned_cg_deck_v1 import canonical_deck_sha256_v1
from .self_owned_cg_package_v1 import (
    PACKAGE_SCHEMA_VERSION_V1,
    SelfOwnedCgPackageV1Error,
    _canonical_json,
    _regular_tree,
    _runtime_file_hashes,
    _semantic_sha,
    _sha256_file,
    _write_exclusive,
    _parse_deck_bytes,
    verify_self_owned_cg_package_v1,
)


SCHEMA = "cg-deck-adaptive-config-v1"
RENDERER_FAMILY = "cg-deck-adaptive-public-state-v1"
_AUTHORITY_FALSE = {
    "training_allowed": False,
    "promotion_allowed": False,
    "submission_allowed": False,
}

PARAMETER_BOUNDS: dict[str, tuple[int, int]] = {
    "setup_basic_bonus": (0, 30_000),
    "setup_stage_bonus": (0, 30_000),
    "play_pokemon_bonus": (0, 30_000),
    "play_supporter_bonus": (0, 30_000),
    "play_item_bonus": (0, 30_000),
    "play_stadium_bonus": (0, 20_000),
    "evolve_bonus": (0, 40_000),
    "attack_lethal_bonus": (0, 30_000),
    "attack_damage_weight_milli": (500, 2_000),
    "attack_energy_efficiency_bonus": (-10_000, 10_000),
    "retreat_damaged_bonus": (-10_000, 30_000),
    "attach_reserve_penalty": (-30_000, 0),
    "search_stage_bonus": (0, 30_000),
    "end_penalty": (-100_000, -1_000),
}


@dataclass(frozen=True, slots=True)
class DeckAdaptiveConfig:
    """One bounded point on the generic deck-adaptive policy surface."""

    setup_basic_bonus: int = 18_000
    setup_stage_bonus: int = 12_000
    play_pokemon_bonus: int = 16_000
    play_supporter_bonus: int = 13_000
    play_item_bonus: int = 9_000
    play_stadium_bonus: int = 7_000
    evolve_bonus: int = 24_000
    attack_lethal_bonus: int = 24_000
    attack_damage_weight_milli: int = 1_000
    attack_energy_efficiency_bonus: int = 0
    retreat_damaged_bonus: int = 8_000
    attach_reserve_penalty: int = -8_000
    search_stage_bonus: int = 15_000
    end_penalty: int = -50_000

    @classmethod
    def default(cls) -> "DeckAdaptiveConfig":
        return cls()

    @classmethod
    def from_mapping(cls, values: Mapping[str, object]) -> "DeckAdaptiveConfig":
        if not isinstance(values, Mapping):
            raise ValueError("deck-adaptive config must be a mapping")
        names = {field.name for field in fields(cls)}
        unknown = set(values) - names
        if unknown:
            raise ValueError(f"unknown parameter(s): {sorted(unknown)}")
        merged = cls.default().as_dict()
        merged.update(values)
        config = cls(**merged)
        config.validate()
        return config

    def as_dict(self) -> dict[str, int]:
        return {field.name: int(getattr(self, field.name)) for field in fields(self)}

    def validate(self) -> None:
        for name, (lower, upper) in PARAMETER_BOUNDS.items():
            value = getattr(self, name)
            if isinstance(value, bool) or not isinstance(value, int):
                raise ValueError(f"parameter {name} must be an integer")
            if not lower <= value <= upper:
                raise ValueError(f"parameter {name} out of bounds: {value}")

    def canonical_json(self) -> str:
        self.validate()
        return json.dumps(
            {"schema_version": SCHEMA, "parameters": self.as_dict()},
            ensure_ascii=False,
            sort_keys=True,
            separators=(",", ":"),
        )

    def config_sha256(self) -> str:
        return hashlib.sha256(self.canonical_json().encode("utf-8")).hexdigest()


def candidate_id_for_config(
    config: DeckAdaptiveConfig, *, generation: int, index: int, deck_sha256: str
) -> str:
    config.validate()
    if type(generation) is not int or type(index) is not int or generation < 0 or index < 0:
        raise ValueError("generation and index must be non-negative integers")
    if type(deck_sha256) is not str or len(deck_sha256) != 64:
        raise ValueError("deck_sha256 must be a SHA-256 string")
    identity = hashlib.sha256(
        (config.config_sha256() + "\0" + deck_sha256).encode("ascii")
    ).hexdigest()[:12]
    return f"cg-deck-adaptive-g{generation:02d}-c{index:02d}-{identity}"


def _deck_literal(deck_ids: Sequence[int]) -> str:
    values = tuple(int(value) for value in deck_ids)
    if len(values) != 60 or any(value <= 0 for value in values):
        raise ValueError("deck_ids must contain exactly 60 positive integers")
    return repr(values)


def _source_template(config: DeckAdaptiveConfig, deck_ids: Sequence[int], candidate_id: str) -> str:
    config.validate()
    if not isinstance(candidate_id, str) or not candidate_id.strip():
        raise ValueError("candidate_id must be non-empty")
    config_json = json.dumps(config.as_dict(), ensure_ascii=False, sort_keys=True, separators=(",", ":"))
    candidate_json = json.dumps(candidate_id, ensure_ascii=False)
    deck_literal = _deck_literal(deck_ids)
    return f'''# Generated by {RENDERER_FAMILY}; research-only.
from __future__ import annotations

from pathlib import Path

from cg.api import AreaType, OptionType, SelectContext, all_attack, all_card_data, to_observation_class

ROOT_DECK = {deck_literal}
_CG_DECK_ADAPTIVE_PARAMETERS = {config_json}
_CG_DECK_ADAPTIVE_CONFIG_SHA256 = {config.config_sha256()!r}
_CG_DECK_ADAPTIVE_CANDIDATE_ID = {candidate_json}
_CG_DECK_ADAPTIVE_RENDERER_FAMILY = {RENDERER_FAMILY!r}
_DECK_COUNTS = {{card_id: ROOT_DECK.count(card_id) for card_id in set(ROOT_DECK)}}
_CARD_DB = {{card.cardId: card for card in all_card_data()}}
_ATTACK_DB = {{attack.attackId: attack for attack in all_attack()}}


def _value(name: str) -> int:
    return int(_CG_DECK_ADAPTIVE_PARAMETERS[name])


def _deck_path() -> Path:
    local = Path(__file__).resolve().with_name("deck.csv")
    for candidate in (local, Path("deck.csv"), Path("/kaggle_simulations/agent/deck.csv")):
        if candidate.is_file():
            return candidate
    raise RuntimeError("deck.csv not found")


def _read_deck() -> list[int]:
    values = [int(token) for token in _deck_path().read_text(encoding="utf-8").split() if token.strip()]
    if len(values) != 60 or any(value <= 0 for value in values):
        raise ValueError("deck must contain exactly 60 positive card IDs")
    return values


def _mine(obs):
    return obs.current.players[obs.current.yourIndex]


def _opponent(obs):
    return obs.current.players[1 - obs.current.yourIndex]


def _energy_count(card: object | None) -> int:
    if card is None:
        return 0
    attached = getattr(card, "energyCards", None)
    return len(attached) if attached is not None else len(getattr(card, "energies", []) or [])


def _damage(card: object | None) -> int:
    if card is None:
        return 0
    try:
        return max(0, int(getattr(card, "maxHp", getattr(card, "hp", 0))) - int(getattr(card, "hp", 0)))
    except Exception:
        return 0


def _card_data(card_id: object) -> object | None:
    return _CARD_DB.get(card_id) if isinstance(card_id, int) else None


def _card_for_area(obs, area: object, index: object, player_index: object | None = None):
    if not isinstance(index, int):
        return None
    owner = obs.current.yourIndex if not isinstance(player_index, int) else player_index
    if owner < 0 or owner >= len(obs.current.players):
        return None
    state = obs.current.players[owner]
    if area == AreaType.HAND:
        cards = state.hand or []
    elif area == AreaType.DISCARD:
        cards = state.discard or []
    elif area == AreaType.ACTIVE:
        cards = state.active or []
    elif area == AreaType.BENCH:
        cards = state.bench or []
    elif area == AreaType.PRIZE:
        cards = state.prize or []
    elif area == AreaType.LOOKING:
        cards = obs.current.looking or []
    elif area == AreaType.STADIUM:
        cards = obs.current.stadium or []
    else:
        return None
    return cards[index] if 0 <= index < len(cards) else None


def _card_for_option(obs, option: object) -> object | None:
    return _card_for_area(
        obs,
        getattr(option, "area", AreaType.HAND) if getattr(option, "type", None) != OptionType.PLAY else AreaType.HAND,
        getattr(option, "index", None),
        getattr(option, "playerIndex", None),
    )


def _target_for_option(obs, option: object) -> object | None:
    area = getattr(option, "inPlayArea", None)
    index = getattr(option, "inPlayIndex", None)
    if area not in {{AreaType.ACTIVE, AreaType.BENCH}} or not isinstance(index, int):
        return None
    state = _mine(obs)
    cards = state.active if area == AreaType.ACTIVE else state.bench
    return cards[index] if 0 <= index < len(cards) else None


def _option_card_id(obs, option: object) -> int | None:
    card = _card_for_option(obs, option)
    card_id = getattr(card, "id", None)
    if isinstance(card_id, int):
        return card_id
    card_id = getattr(option, "cardId", None)
    return card_id if isinstance(card_id, int) else None


def _attack_damage(option: object) -> int:
    attack = _ATTACK_DB.get(getattr(option, "attackId", None))
    return max(0, int(getattr(attack, "damage", 0))) if attack is not None else 0


def _attack_energy_cost(option: object) -> int:
    attack = _ATTACK_DB.get(getattr(option, "attackId", None))
    energies = getattr(attack, "energies", []) if attack is not None else []
    return len(energies or [])


def _stage_score(data: object | None) -> int:
    if data is None or int(getattr(data, "cardType", -1)) != 0:
        return 0
    if bool(getattr(data, "stage2", False)):
        return _value("setup_stage_bonus") + 10_000
    if bool(getattr(data, "stage1", False)):
        return _value("setup_stage_bonus")
    if bool(getattr(data, "basic", False)):
        return _value("setup_basic_bonus")
    return 1_000


def _pokemon_ids(obs) -> set[int]:
    state = _mine(obs)
    return {{int(card.id) for card in ([*(state.active or []), *(state.bench or [])]) if getattr(card, "id", None) is not None}}


def _setup_score(obs, option: object) -> int:
    context = getattr(obs.select, "context", None)
    option_type = getattr(option, "type", None)
    if option_type == OptionType.NO:
        return 20_000 if context == SelectContext.MULLIGAN else 1
    if option_type == OptionType.YES:
        return 10_000 if context == SelectContext.ACTIVATE else 0
    data = _card_data(_option_card_id(obs, option))
    score = _stage_score(data)
    if context == SelectContext.SETUP_ACTIVE_POKEMON:
        return score + int(getattr(data, "hp", 0))
    if context == SelectContext.SETUP_BENCH_POKEMON:
        return score + int(getattr(data, "hp", 0)) // 2
    return score


def _play_score(obs, option: object) -> int:
    data = _card_data(_option_card_id(obs, option))
    card_type = int(getattr(data, "cardType", -1)) if data is not None else -1
    if card_type == 0:
        score = _value("play_pokemon_bonus") + _stage_score(data) + int(getattr(data, "hp", 0))
        if len(_mine(obs).bench or []) >= int(getattr(_mine(obs), "benchMax", 5)):
            return -1_000
        return score
    if card_type == 3:
        return _value("play_supporter_bonus") if not bool(getattr(obs.current, "supporterPlayed", False)) else -10_000
    if card_type == 4:
        return _value("play_stadium_bonus") if not bool(getattr(obs.current, "stadiumPlayed", False)) else -10_000
    if card_type in {{1, 2}}:
        return _value("play_item_bonus")
    return 1_000


def _evolve_score(obs, option: object) -> int:
    data = _card_data(_option_card_id(obs, option))
    target = _target_for_option(obs, option)
    if getattr(target, "appearThisTurn", False):
        return -1_000
    return _value("evolve_bonus") + _stage_score(data) + int(getattr(data, "hp", 0)) if data is not None else 1_000


def _attach_score(obs, option: object) -> int:
    target = _target_for_option(obs, option)
    energy = _energy_count(target)
    score = 8_000 + energy * 1_000
    if energy >= 2:
        score += _value("attach_reserve_penalty")
    if target is not None and _damage(target) > 0:
        score += _value("retreat_damaged_bonus") // 2
    return score


def _main_score(obs, option: object) -> int:
    option_type = getattr(option, "type", None)
    if option_type == OptionType.PLAY:
        return _play_score(obs, option)
    if option_type == OptionType.EVOLVE:
        return _evolve_score(obs, option)
    if option_type == OptionType.ATTACH:
        return _attach_score(obs, option)
    if option_type == OptionType.ATTACK:
        damage = _attack_damage(option)
        active = (_opponent(obs).active or [None])[0]
        hp = int(getattr(active, "hp", 0)) if active is not None else 0
        score = (damage * _value("attack_damage_weight_milli")) // 1000
        if hp > 0 and damage >= hp:
            score += _value("attack_lethal_bonus")
        cost = _attack_energy_cost(option)
        score += _value("attack_energy_efficiency_bonus") * max(0, 3 - cost)
        return score
    if option_type == OptionType.ABILITY:
        return _value("play_pokemon_bonus")
    if option_type == OptionType.RETREAT:
        active = (_mine(obs).active or [None])[0]
        return _value("retreat_damaged_bonus") if _damage(active) > 0 else -1_000
    if option_type == OptionType.END:
        return _value("end_penalty")
    return 1_000


def _search_priority(obs, option: object) -> int:
    data = _card_data(_option_card_id(obs, option))
    if data is None:
        return 1_000
    score = _stage_score(data) + _value("search_stage_bonus")
    if int(getattr(data, "cardType", -1)) == 0:
        score += int(getattr(data, "hp", 0))
    return score


def _non_main_score(obs, option: object) -> int:
    context = getattr(obs.select, "context", None)
    if context in {{SelectContext.TO_HAND, SelectContext.TO_FIELD, SelectContext.TO_BENCH,
                    SelectContext.CARD, SelectContext.LOOK, SelectContext.EVOLVES_TO}}:
        return _search_priority(obs, option)
    if context in {{SelectContext.ATTACH_TO, SelectContext.ATTACH_FROM}}:
        return _attach_score(obs, option)
    if context in {{SelectContext.SWITCH, SelectContext.TO_ACTIVE}}:
        target = _card_for_option(obs, option)
        return _damage(target) + _energy_count(target) * 1_000
    if context in {{SelectContext.DISCARD, SelectContext.DISCARD_CARD_OR_ATTACHED_CARD}}:
        return -_energy_count(_card_for_option(obs, option)) * 2_000
    if context == SelectContext.ATTACK:
        return _attack_damage(option)
    if context in {{SelectContext.NUMBER, SelectContext.DRAW_COUNT}}:
        return int(getattr(option, "number", 0) or 0)
    return 1_000


def _score(obs, option: object) -> int:
    context = getattr(obs.select, "context", None)
    if context in {{SelectContext.IS_FIRST, SelectContext.MULLIGAN,
                    SelectContext.SETUP_ACTIVE_POKEMON, SelectContext.SETUP_BENCH_POKEMON,
                    SelectContext.ACTIVATE}}:
        return _setup_score(obs, option)
    if getattr(option, "type", None) in {{OptionType.YES, OptionType.NO}}:
        return _setup_score(obs, option)
    if context == SelectContext.MAIN:
        return _main_score(obs, option)
    return _non_main_score(obs, option)


def _fallback_raw(obs_dict: dict) -> list[int]:
    select = obs_dict.get("select") if isinstance(obs_dict, dict) else None
    if not isinstance(select, dict):
        return list(ROOT_DECK)
    options = select.get("option")
    minimum = select.get("minCount")
    maximum = select.get("maxCount")
    if not isinstance(options, list) or not isinstance(minimum, int) or not isinstance(maximum, int):
        return []
    count = max(0, min(minimum, maximum, len(options)))
    return list(range(count))


def agent(obs_dict: dict) -> list[int]:
    try:
        obs = to_observation_class(obs_dict)
        if obs.select is None:
            return _read_deck()
        options = list(obs.select.option or [])
        if not options:
            return []
        minimum = max(0, min(int(obs.select.minCount), len(options)))
        maximum = max(minimum, min(int(obs.select.maxCount), len(options)))
        scored = [(int(_score(obs, option)), index) for index, option in enumerate(options)]
        scored.sort(key=lambda pair: (-pair[0], pair[1]))
        selected: list[int] = []
        for score, index in scored:
            if len(selected) >= maximum:
                break
            if score < 0 and len(selected) >= minimum:
                continue
            selected.append(index)
        if len(selected) < minimum:
            selected = [index for _score_value, index in scored[:minimum]]
        return selected[:maximum]
    except Exception:
        return _fallback_raw(obs_dict)
'''


def render_deck_adaptive_source(
    config: DeckAdaptiveConfig, *, deck_ids: Sequence[int], candidate_id: str
) -> str:
    """Return a self-contained generic policy source for one generated deck."""

    return _source_template(config, deck_ids, candidate_id)


def materialize_deck_adaptive_package(
    *,
    source_runtime_package: str | Path,
    deck_package: str | Path,
    output_package: str | Path,
    config: DeckAdaptiveConfig,
    candidate_id: str,
) -> dict[str, object]:
    """Copy only a verified ``cg/`` runtime and bind the adaptive policy/deck."""

    config.validate()
    source = Path(source_runtime_package).resolve()
    deck_root = Path(deck_package).resolve()
    target = Path(output_package).resolve()
    runtime_root = source / "cg"
    if not runtime_root.is_dir():
        raise SelfOwnedCgPackageV1Error("source runtime package has no cg directory")
    _regular_tree(runtime_root)
    deck_manifest = verify_self_owned_cg_package_v1(deck_root)
    deck_path = deck_root / "deck.csv"
    deck_bytes = deck_path.read_bytes()
    deck_ids = _parse_deck_bytes(deck_bytes)
    if canonical_deck_sha256_v1(deck_ids) != deck_manifest.get("canonical_deck_sha256"):
        raise SelfOwnedCgPackageV1Error("deck manifest canonical hash mismatch")
    if target.exists() or target.is_symlink():
        raise FileExistsError(f"output package already exists: {target}")
    target.mkdir(parents=True, exist_ok=False)
    shutil.copytree(runtime_root, target / "cg", symlinks=False)
    (target / "main.py").write_text(
        render_deck_adaptive_source(config, deck_ids=deck_ids, candidate_id=candidate_id),
        encoding="utf-8",
    )
    (target / "deck.csv").write_bytes(deck_bytes)
    payload: dict[str, object] = {
        "schema_version": PACKAGE_SCHEMA_VERSION_V1,
        "candidate_id": candidate_id,
        "archetype_id": "self-owned-cg-deck-adaptive",
        "parent_deck": None,
        "public_parent_read": False,
        "parent_policy_sha256": hashlib.sha256(RENDERER_FAMILY.encode("ascii")).hexdigest(),
        "policy_sha256": _sha256_file(target / "main.py"),
        "deck_file_sha256": _sha256_file(target / "deck.csv"),
        "canonical_deck_sha256": canonical_deck_sha256_v1(deck_ids),
        "root_deck_replaced": True,
        "runtime_files": {
            f"cg/{relative}": digest
            for relative, digest in _runtime_file_hashes(target / "cg").items()
        },
        "research_only": True,
        "authority": dict(_AUTHORITY_FALSE),
    }
    payload["manifest_sha256"] = _semantic_sha(payload)
    _write_exclusive(target / "self_owned_cg_package_manifest.json", _canonical_json(payload))
    return payload


__all__ = [
    "DeckAdaptiveConfig",
    "PARAMETER_BOUNDS",
    "RENDERER_FAMILY",
    "SCHEMA",
    "candidate_id_for_config",
    "materialize_deck_adaptive_package",
    "render_deck_adaptive_source",
]
